### ISSUE TITLE
URL error

### ISSUE THREAD

**Issue by chascos69** [mgks/Android-SmartWebView#1]
Hello 

This website open in external webbroser: https://www.i-moments.com/online/80050/?origen=app
This website not working: http://imagen.online-convert.com/es/convertir-a-jpg

Can  you response to scascales@ageinfo.es? Thx!

**Comment by mgks** [comment]
Your URLs redirect from one URL to another, not one, but both of them.
It goes like this, host to host:

> https://www.i-moments.com

then,

> http://www.i-moments.com

then again,

> http://services.imaxel.com

and again,

> http://galleries.iws.imaxel.com

and at last it shows a blank page, which is none of my concern or business. Same issue with the other URL, although it's working fine but your converted file requests to open another URL.

This project is made to provide best user experience through webview that's why external URLs are designed to open in default browser, but still, if you want to do all the redirection inside the app, remove:

```
... else if (!url.startsWith(ASWV_URL)) {
       Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(url));
       startActivity(intent);
} ...
```
mentioned inside `shouldOverrideUrlLoading()` method.
