### ISSUE TITLE
facebook share from webview

### ISSUE THREAD

**Issue by pmaojo** [mgks/Android-SmartWebView#4]
Hi, my app is like a newspaper, and articles have simple links to share on facebook and other social networks. When I click on the share on facebook button, it opens Facebook on a browser, does not try to use native Facebook app. Is there a way to intercept that link and open the facebook app with the link to share? maybe using facebook sdk? sorry Im so new on android dev...

Plus go back to my app afterwards.

**Comment by mgks** [comment]
Hi, I just added a new portion to the codes to share URLs but here's the catch.
You will be able to share your links to external apps with pattern of URL `share:http://shareable_web_url` but as I suppose you must be using your app as a browser based app too, that will cause the problem using this (`share:`) patch. But, there are still many ways to outsmart the system.

Let me give you a hint, as my recent change to the script, I added this piece of code which checks for hyperlink requests starting with `share:` and continued with desired URL.

```
if (url.startsWith("share:")) {
    Intent intent = new Intent(Intent.ACTION_SEND);
    intent.setType("text/plain");
    intent.putExtra(Intent.EXTRA_SUBJECT, view.getTitle());
    intent.putExtra(Intent.EXTRA_TEXT, view.getTitle()+"\nVisit: "+(Uri.parse(url).toString()).replace("share:",""));
    startActivity(Intent.createChooser(intent, "Share with your Friends"));
}
```

It can fulfill a wide range of desired work but you can modify it as your need to check for specific URLs instead of using `share:` as:

```
if(url.contains("facebook.com|twitter.com|plus.google.com"))
```

It will also launch the same share to all social media intent but atleast you don't have to make any changes to your app. The possibilities are infinite, keep testing and let me know when you made it.

**Comment by pmaojo** [comment]
Thankyou! 
Yes, the app is a mobile focused responsive website. The "share:" solution can fit becouse I can make use of custom User Agent to show the share link to the app only.  I will update as soon as I test it.
