### ISSUE TITLE
Connection may not be available or slow

### ISSUE THREAD

**Issue by nikolas27** [mgks/Android-SmartWebView#89]
Hello, Thanks a lot for your lovely project.
I made an app for my webpage, following your instructions without adding or changing anything.
Now when i export the app ask apk, i get the following error: " please check your internet connection, connection may not be available or slow. Tap here to try again"

Any ideas?

**Comment by smohannagaraj** [comment]
Reasons:
- You removed the permission for internet access in [AndroidManifest File](https://github.com/mgks/Android-SmartWebView/blob/2fe40665884bba87e662ca5144f59de1717204b7/app/src/main/AndroidManifest.xml#L26)
- Incorrect url entered in [SmartWebView.java](https://github.com/mgks/Android-SmartWebView/blob/2fe40665884bba87e662ca5144f59de1717204b7/app/src/main/java/mgks/os/webview/SmartWebView.java#L65)
- Also check http or https.
- Did you tried it in android studio emulator?  This happen only when exporting as apk or always?

Could you give more other clues to guess what the problem is?

**Comment by nikolas27** [comment]
Thanks a lot for your response.
I had the URL incorrect on smarwebview.java.
now that I've corrected it, the app is blank and it opens the URL on chrome.
Any ideas?

**Comment by smohannagaraj** [comment]
Check this also:
- [Android Manifest File](https://github.com/mgks/Android-SmartWebView/blob/2fe40665884bba87e662ca5144f59de1717204b7/app/src/main/AndroidManifest.xml#L63)
- [SmartWebView.java](https://github.com/mgks/Android-SmartWebView/blob/2fe40665884bba87e662ca5144f59de1717204b7/app/src/main/java/mgks/os/webview/SmartWebView.java#L53)

Here what the problem is:
- You gave different urls in different files.  Eg. http or https & example.com and example.com/ are different.
- So as given in the second list, by default external urls open in chrome.  That is, your webview url is recognised as external url. 
- I suggest use "find" tool in android studio with word "https" or "www" ".com".  This will help you to identify your problem.

**Comment by smohannagaraj** [comment]
> Maybe because the page is actually redirecting visitors to login page?

Sorry.  In previous reply, I missed this point.  I think your page url and login url are different.  Make [this](https://github.com/mgks/Android-SmartWebView/blob/2fe40665884bba87e662ca5144f59de1717204b7/app/src/main/java/mgks/os/webview/SmartWebView.java#L53) as false.  This will work.
Note:  This will make all urls e.g. facebook, insta opens in webview.  To escape this, you need some lines of code.  If you want, surely you can ask me for it.  Welcome for your thanks.

**Comment by nikolas27** [comment]
Thanks a lot for your effort, can i have the line of code for facebook login?

**Comment by smohannagaraj** [comment]
First say something about the login re-direction. Is this is different host or domain?
I have some works.  I will tomorrow.

**Comment by nikolas27** [comment]
it is domain.com to domain.com/login

Ideally all the external pages should be opened externaly and all the internal ones, internally (on web-view)

Thanks once again

**Comment by smohannagaraj** [comment]
It looks like the same domain.  so the problem is still problem, try again [this](https://github.com/mgks/Android-SmartWebView/issues/89#issuecomment-502440077)

**Comment by nikolas27** [comment]
Thanks, can i have the code for FB login please? :)

**Comment by smohannagaraj** [comment]
> it is domain.com to domain.com/login

Both are in same domain.  Could you paste the manifest file and android webview file?

If you just started your project, I would suggest you may start fresh.  I think this mistake is a typo error.

**Comment by nikolas27** [comment]
Hello, it is done now.
The problem was that the redirection was attaching an www (https://www.domain.com) to the domain. Now everything works fine exept of the facebook login.

While the user opens the app and clicks on "FB login", he is redirected to the "FB page" which opens externaly, but when he puts his credentials (username/pass) the address opens as a webpage in chrome.

1) any ideas on how to make FB login work?
2) how can I edit or remove the splash screen?

Thanks a lot in advance :)

**Comment by smohannagaraj** [comment]
Chane [this](https://github.com/mgks/Android-SmartWebView/blob/2fe40665884bba87e662ca5144f59de1717204b7/app/src/main/java/mgks/os/webview/MainActivity.java#L525) line
From : 
} else if (ASWP_EXTURL && !aswm_host(url).equals(ASWV_HOST)) {
To : 
} else if (ASWP_EXTURL && !aswm_host(url).equals(ASWV_HOST) && !aswm_host(url).contains('facebook.com') ) {

Warning : Don't keep any facebook links or provide the login subdomain of facebook above.  Otherwise your app will open facebook page and use can use it like a facebook app.
All the best!

**Comment by nikolas27** [comment]
Thanks so much for your effort. It was very helpful. All the best :)

**Comment by smohannagaraj** [comment]
> Thanks so much for your effort. It was very helpful. All the best :)

Is it working??????

**Comment by nikolas27** [comment]
haven't tried it cause FB advises against FB login in web-view. I am just thanking you for your answer
